pipeline {
    agent any

    environment { 
        IMAGE = "18.220.217.117:8081/php-hosted"
        SONAR_SERVER = "sonar"
        NEXUS_URL = "18.220.217.117:8081"
    }

    stages {

        stage('Checkout') {
            steps {
               checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'github-cred', url: 'https://github.com/satya1031/php-ecommerce-devops.git']])
            }
        }

       stage('Sonar Scan') {
    steps {
        withSonarQubeEnv('sonar') {
            withCredentials([string(credentialsId: 'sonar-cred', variable: 'SONAR_TOKEN')]) {
                sh """
                ${tool 'sonar-scanner'}/bin/sonar-scanner \
                -Dsonar.projectKey=php-ecommerce \
                -Dsonar.sources=. \
                -Dsonar.host.url=http://18.220.217.117:9000 \
                -Dsonar.login=$SONAR_TOKEN
                """
            }
        }
    }
}

      
        stage('Build Docker Image') {
    steps {
        sh '''
        docker build -t $IMAGE:$BUILD_NUMBER -f docker/Dockerfile .
        '''
    }
}

       stage('Push to Nexus') {
    steps {
        withCredentials([usernamePassword(
            credentialsId: 'nexus-cred',
            usernameVariable: 'NEXUS_USER',
            passwordVariable: 'NEXUS_PASS'
        )]) {
            sh '''
            echo $NEXUS_PASS | docker login 18.220.217.117:8083 -u $NEXUS_USER --password-stdin
            docker push 18.220.217.117:8083/docker-hosted/php-hosted:$BUILD_NUMBER
            '''
        }
    }
}

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                export KUBECONFIG=/var/lib/jenkins/.kube/config
        
                kubectl get nodes
        
                sed -i 's|IMAGE_TAG|$BUILD_NUMBER|g' k8s/deployment.yaml
        
                kubectl apply -f k8s/
                """
            }
        }
    }

    post {
        success {
            echo "Deployment Successful"
        }
        failure {
            echo "Pipeline Failed"
        }
    }
}
